// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneGround.ZGW.Besluiten.DataModel;

#nullable disable

namespace OneGround.ZGW.Besluiten.DataModel.Migrations
{
    [DbContext(typeof(BrcDbContext))]
    [Migration("20250506154504_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:ci_collation", "@colStrength=secondary,@colStrength=secondary,icu,False")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneGround.ZGW.Besluiten.DataModel.Besluit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BesluitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("besluittype")
                        .UseCollation("ci_collation");

                    b.Property<string>("BestuursOrgaan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bestuursorgaan");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<string>("Identificatie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificatie");

                    b.Property<DateOnly>("IngangsDatum")
                        .HasColumnType("date")
                        .HasColumnName("ingangsdatum");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.Property<DateOnly?>("PublicatieDatum")
                        .HasColumnType("date")
                        .HasColumnName("publicatiedatum");

                    b.Property<string>("Toelichting")
                        .HasColumnType("text")
                        .HasColumnName("toelichting");

                    b.Property<DateOnly?>("UiterlijkeReactieDatum")
                        .HasColumnType("date")
                        .HasColumnName("uiterlijkeReactiedatum");

                    b.Property<string>("VerantwoordelijkeOrganisatie")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("verantwoordelijkeorganisatie");

                    b.Property<DateOnly?>("VervalDatum")
                        .HasColumnType("date")
                        .HasColumnName("vervaldatum");

                    b.Property<int?>("VervalReden")
                        .HasColumnType("integer")
                        .HasColumnName("vervalreden");

                    b.Property<DateOnly?>("VerzendDatum")
                        .HasColumnType("date")
                        .HasColumnName("verzenddatum");

                    b.Property<string>("Zaak")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("zaak")
                        .UseCollation("ci_collation");

                    b.Property<string>("ZaakBesluitUrl")
                        .HasColumnType("text")
                        .HasColumnName("zaakbesluit");

                    b.HasKey("Id");

                    b.HasIndex("BesluitType");

                    b.HasIndex("Identificatie");

                    b.HasIndex("VerantwoordelijkeOrganisatie");

                    b.HasIndex("Zaak");

                    b.HasIndex("Owner", "Identificatie");

                    b.HasIndex("VerantwoordelijkeOrganisatie", "Identificatie")
                        .IsUnique();

                    b.ToTable("besluiten");
                });

            modelBuilder.Entity("OneGround.ZGW.Besluiten.DataModel.BesluitAuthorization", b =>
                {
                    b.Property<string>("BesluitType")
                        .HasColumnType("text");

                    b.ToTable("#BesluitAuthorization", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("OneGround.ZGW.Besluiten.DataModel.BesluitInformatieObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AardRelatie")
                        .HasColumnType("integer")
                        .HasColumnName("aardrelatie");

                    b.Property<Guid>("BesluitId")
                        .HasColumnType("uuid")
                        .HasColumnName("besluit_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("InformatieObject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("informatieobject")
                        .UseCollation("ci_collation");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.Property<DateOnly>("Registratiedatum")
                        .HasColumnType("date")
                        .HasColumnName("registratiedatum");

                    b.HasKey("Id");

                    b.HasIndex("BesluitId");

                    b.HasIndex("InformatieObject");

                    b.ToTable("besluitinformatieobjecten");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.AuditTrail.AuditTrailRegel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AanmaakDatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aanmaakdatum");

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actie");

                    b.Property<string>("ActieWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actieweergave");

                    b.Property<string>("ApplicatieId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicatie_id");

                    b.Property<string>("ApplicatieWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicatieweergave");

                    b.Property<string>("Bron")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bron");

                    b.Property<string>("GebruikersId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gebruikers_id");

                    b.Property<string>("GebruikersWeergave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gebruikersweergave");

                    b.Property<string>("HoofdObject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hoofdobject");

                    b.Property<Guid?>("HoofdObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoofdobject_id");

                    b.Property<string>("Nieuw")
                        .HasColumnType("jsonb")
                        .HasColumnName("nieuw");

                    b.Property<string>("Oud")
                        .HasColumnType("jsonb")
                        .HasColumnName("oud");

                    b.Property<string>("RequestId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resourceurl");

                    b.Property<string>("ResourceWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceweergave");

                    b.Property<int>("Resultaat")
                        .HasColumnType("integer")
                        .HasColumnName("resultaat");

                    b.Property<string>("Toelichting")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("toelichting");

                    b.HasKey("Id");

                    b.HasIndex("HoofdObjectId");

                    b.ToTable("audittrail");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.Migrations.FinishedDataMigration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("text")
                        .HasColumnName("application_version");

                    b.Property<DateTime>("Executed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("finished_data_migrations");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.NumberGenerator.OrganisatieNummer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("EntiteitNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entiteit");

                    b.Property<string>("Formaat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formaat");

                    b.Property<long>("HuidigNummer")
                        .HasColumnType("bigint")
                        .HasColumnName("huidig_nummer");

                    b.Property<string>("HuidigNummerEntiteit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("huidig_nummer_entiteit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("Rsin")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("rsin");

                    b.HasKey("Id");

                    b.ToTable("organisatie_nummers");
                });

            modelBuilder.Entity("OneGround.ZGW.Besluiten.DataModel.BesluitInformatieObject", b =>
                {
                    b.HasOne("OneGround.ZGW.Besluiten.DataModel.Besluit", "Besluit")
                        .WithMany("BesluitInformatieObjecten")
                        .HasForeignKey("BesluitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Besluit");
                });

            modelBuilder.Entity("OneGround.ZGW.Besluiten.DataModel.Besluit", b =>
                {
                    b.Navigation("BesluitInformatieObjecten");
                });
#pragma warning restore 612, 618
        }
    }
}
