// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Keycloak.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EvaluationResultRepresentation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowedScopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.Client.Models.ScopeRepresentation>? AllowedScopes { get; set; }
#nullable restore
#else
        public List<global::Keycloak.Client.Models.ScopeRepresentation> AllowedScopes { get; set; }
#endif
        /// <summary>The deniedScopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.Client.Models.ScopeRepresentation>? DeniedScopes { get; set; }
#nullable restore
#else
        public List<global::Keycloak.Client.Models.ScopeRepresentation> DeniedScopes { get; set; }
#endif
        /// <summary>The policies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.Client.Models.PolicyResultRepresentation>? Policies { get; set; }
#nullable restore
#else
        public List<global::Keycloak.Client.Models.PolicyResultRepresentation> Policies { get; set; }
#endif
        /// <summary>The resource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Keycloak.Client.Models.ResourceRepresentation? Resource { get; set; }
#nullable restore
#else
        public global::Keycloak.Client.Models.ResourceRepresentation Resource { get; set; }
#endif
        /// <summary>The scopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.Client.Models.ScopeRepresentation>? Scopes { get; set; }
#nullable restore
#else
        public List<global::Keycloak.Client.Models.ScopeRepresentation> Scopes { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Keycloak.Client.Models.DecisionEffect? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Keycloak.Client.Models.EvaluationResultRepresentation"/> and sets the default values.
        /// </summary>
        public EvaluationResultRepresentation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Keycloak.Client.Models.EvaluationResultRepresentation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Keycloak.Client.Models.EvaluationResultRepresentation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Keycloak.Client.Models.EvaluationResultRepresentation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowedScopes", n => { AllowedScopes = n.GetCollectionOfObjectValues<global::Keycloak.Client.Models.ScopeRepresentation>(global::Keycloak.Client.Models.ScopeRepresentation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "deniedScopes", n => { DeniedScopes = n.GetCollectionOfObjectValues<global::Keycloak.Client.Models.ScopeRepresentation>(global::Keycloak.Client.Models.ScopeRepresentation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "policies", n => { Policies = n.GetCollectionOfObjectValues<global::Keycloak.Client.Models.PolicyResultRepresentation>(global::Keycloak.Client.Models.PolicyResultRepresentation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resource", n => { Resource = n.GetObjectValue<global::Keycloak.Client.Models.ResourceRepresentation>(global::Keycloak.Client.Models.ResourceRepresentation.CreateFromDiscriminatorValue); } },
                { "scopes", n => { Scopes = n.GetCollectionOfObjectValues<global::Keycloak.Client.Models.ScopeRepresentation>(global::Keycloak.Client.Models.ScopeRepresentation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Keycloak.Client.Models.DecisionEffect>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Keycloak.Client.Models.ScopeRepresentation>("allowedScopes", AllowedScopes);
            writer.WriteCollectionOfObjectValues<global::Keycloak.Client.Models.ScopeRepresentation>("deniedScopes", DeniedScopes);
            writer.WriteCollectionOfObjectValues<global::Keycloak.Client.Models.PolicyResultRepresentation>("policies", Policies);
            writer.WriteObjectValue<global::Keycloak.Client.Models.ResourceRepresentation>("resource", Resource);
            writer.WriteCollectionOfObjectValues<global::Keycloak.Client.Models.ScopeRepresentation>("scopes", Scopes);
            writer.WriteEnumValue<global::Keycloak.Client.Models.DecisionEffect>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
