// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Keycloak.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UPConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.Client.Models.UPAttribute>? Attributes { get; set; }
#nullable restore
#else
        public List<global::Keycloak.Client.Models.UPAttribute> Attributes { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Keycloak.Client.Models.UPGroup>? Groups { get; set; }
#nullable restore
#else
        public List<global::Keycloak.Client.Models.UPGroup> Groups { get; set; }
#endif
        /// <summary>The unmanagedAttributePolicy property</summary>
        public global::Keycloak.Client.Models.UnmanagedAttributePolicy? UnmanagedAttributePolicy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Keycloak.Client.Models.UPConfig"/> and sets the default values.
        /// </summary>
        public UPConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Keycloak.Client.Models.UPConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Keycloak.Client.Models.UPConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Keycloak.Client.Models.UPConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::Keycloak.Client.Models.UPAttribute>(global::Keycloak.Client.Models.UPAttribute.CreateFromDiscriminatorValue)?.AsList(); } },
                { "groups", n => { Groups = n.GetCollectionOfObjectValues<global::Keycloak.Client.Models.UPGroup>(global::Keycloak.Client.Models.UPGroup.CreateFromDiscriminatorValue)?.AsList(); } },
                { "unmanagedAttributePolicy", n => { UnmanagedAttributePolicy = n.GetEnumValue<global::Keycloak.Client.Models.UnmanagedAttributePolicy>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Keycloak.Client.Models.UPAttribute>("attributes", Attributes);
            writer.WriteCollectionOfObjectValues<global::Keycloak.Client.Models.UPGroup>("groups", Groups);
            writer.WriteEnumValue<global::Keycloak.Client.Models.UnmanagedAttributePolicy>("unmanagedAttributePolicy", UnmanagedAttributePolicy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
