name: Build and Publish a Docker Image

on:
  workflow_call:
    inputs:
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      git_tag_name:
        required: true
        type: string
        description: 'Tag name for the Docker image'
      services:
        required: true
        type: string
        description: 'A JSON array of service objects. Each object must have "service_name", "docker_file", and "context" keys.'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  GITHUB_REGISTRY: ghcr.io
  ORGANIZATION: oneground

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(inputs.services) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PowerShell
        uses: PSModule/install-powershell@v1
        with:
          Version: 7.5.0

      - name: Get next application version
        id: get_application_version
        shell: pwsh
        run: >-
          ./.github/scripts/Get-NextApplicationVersion.ps1
          -ServiceName "${{ inputs.git_tag_name }}"
          -MajorVersion "${{ inputs.major_version }}"
          -MinorVersion "${{ inputs.minor_version }}"

      - name: Build and push Docker image for ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.docker_file }}
          push: true
          provenance: false
          tags: "${{ env.GITHUB_REGISTRY }}/${{ env.ORGANIZATION }}/${{ matrix.service.service_name }}:${{ steps.get_application_version.outputs.version }}"

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ inputs.git_tag_name }}@${{ steps.get_application_version.outputs.version }}" -m "Release version ${{ steps.get_application_version.outputs.version }}"
          git push origin "${{ inputs.git_tag_name }}@${{ steps.get_application_version.outputs.version }}"
