#
# Docker Compose for the OneGround Besluiten API (BRC).
#
# This file defines the BRC service container. For full setup instructions,
# please refer to the README.md file.
#
name: oneground-besluiten-api

services:
  oneground.besluiten.webapi:
    image: ghcr.io/oneground/besluiten-api:1.0
    restart: unless-stopped
    ports:
      # You can change the host port (5013) if it conflicts with another service.
      - "5013:5000"
    env_file:
      - ".env"
    networks:
      - external_network

networks:
  external_network:
    # IMPORTANT: This must connect to the same network as your other services
    # (Postgres, RabbitMQ, Redis) for the API to function.
    name: bridge # <-- CHANGE THIS to your existing network name.
    external: true
