services:
  oneground-certificates-generator:
    build:
      context: ./oneground-certificates-generator
      dockerfile: Dockerfile
    image: oneground-certificates-generator
    volumes:
      - ./oneground-certificates:/certs