name: oneground-local

services:
  oneground-certificates-generator:
    build:
      context: ../tools/oneground-certificates-generator
      dockerfile: Dockerfile
    volumes:
      - ./oneground-certificates:/certs

  haproxy:
    image: haproxy:2.2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HAPROXY_CONFIG_PATH}:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ${ONEGROUND_CERTIFICATES_PATH}:/etc/ssl/certs:ro
    restart: unless-stopped
    depends_on:
      oneground-certificates-generator:
        condition: service_completed_successfully
    networks:
      oneground:
        aliases:
          - ${NRC_HOST}
          - ${ZTC_HOST}
          - ${ZRC_HOST}
          - ${DRC_HOST}
          - ${BRC_HOST}
          - ${RC_HOST}
          - ${AC_HOST}
          - ${NRC_LISTENER_HOST}
          - ${DRC_LISTENER_HOST}
          - ${HAPROXY_HOST}
          - ${KEYCLOAK_HOST}
          - ${RABBIT_MQ_HOST}

  rabbit_mq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - ${EVENTBUS_MANAGING_PORT}:15672
      - ${EVENTBUS_MESSAGING_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_VHOST: "${EVENTBUS_VIRTUAL_HOST}"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    networks:
      - oneground

  postgres_docker_db:
    build:
      context: postgresql/.
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql/init-database.sh:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
      TZ: "Europe/Amsterdam"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_SUPER_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - oneground

  redis:
    image: redis:6.0.10-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 8
      start_period: 10s
    networks:
      - oneground

  ceph:
    image: ceph/daemon:latest-octopus
    command: demo
    environment:
      MON_IP: 127.0.0.1
      CEPH_PUBLIC_NETWORK: 0.0.0.0/0
      CEPH_DEMO_UID: demo
      CEPH_DEMO_ACCESS_KEY: demo
      CEPH_DEMO_SECRET_KEY: demo
      CEPH_DEMO_BUCKET: "${CEPH_DEMO_BUCKET}"
      CEPH_DEMO_DASHBOARD_USER: "${CEPH_DEMO_DASHBOARD_USER}"
      CEPH_DEMO_DASHBOARD_PASSWORD: "${CEPH_DEMO_DASHBOARD_PASSWORD}"
    volumes:
      - ./ceph/demo.sh:/opt/ceph-container/bin/demo.sh
      - ceph-etc:/etc/ceph
      - ceph-lib:/var/lib/ceph/
    ports:
      - 8443:8443
      - 5000:5000
      - 8888:8888
    networks:
      - oneground

  keycloak-provider-downloader:
    image: alpine:3.22
    command: sh -c "if [ -f /providers/zgw-token-introspection.jar ]; then echo 'JAR present'; else wget -q -O /providers/zgw-token-introspection.jar https://github.com/OneGround/Keycloak-ZGW-Token-Introspection/releases/download/v1/zgw-token-introspection.jar && chmod 644 /providers/zgw-token-introspection.jar; fi"
    volumes:
      - kc-providers:/providers
    restart: "no"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    restart: unless-stopped
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KEYCLOAK_LOGLEVEL=debug
      - KC_DB=postgres
      - KC_DB_DATABASE=keycloak
      - KC_DB_USERNAME=${POSTGRES_SUPER_USER}
      - KC_DB_PASSWORD=${POSTGRES_SUPER_USER_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://postgres_docker_db:5432/keycloak?currentSchema=keycloak
      - KC_HEALTH_ENABLED=true
    ports:
      - "${KEYCLOAK_PORT}:8080"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { java.net.URI uri = java.net.URI.create(args[0]); System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)uri.toURL().openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/ready']
      interval: 5s
      timeout: 5s
      retries: 8
      start_period: 5s
    command: ["start-dev"]
    volumes:
      - kc-providers:/opt/keycloak/providers:ro
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      keycloak-provider-downloader:
        condition: service_completed_successfully
    networks:
      - oneground

  keycloak-setup:
    build:
      context: keycloak/.
      dockerfile: KeycloakSetup/Dockerfile
    environment:
      Keycloak__BaseUrl: http://keycloak:${KEYCLOAK_PORT}
      Keycloak__AdminUsername: ${KEYCLOAK_ADMIN_USERNAME}
      Keycloak__AdminPassword: ${KEYCLOAK_ADMIN_PASSWORD}
      Keycloak__RealmName: OneGround
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - oneground

  zgw.autorisaties.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Autorisaties.WebApi/Dockerfile
    user: root
    volumes:
      - ./oneground-services-data/ac-data:/app/data
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Autorisaties.WebApi
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${AC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      SeedData__Applicaties: "/app/data/applicaties.json"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_AC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_AC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

  zgw.besluiten.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Besluiten.WebApi/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Besluiten.WebApi
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${BRC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_BRC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_BRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

  zgw.catalogi.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Catalogi.WebApi/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Catalogi.WebApi
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${ZTC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_ZTC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_ZTC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

  zgw.documenten.messaging.listener:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Documenten.Messaging.Listener/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Documenten.Messaging.Listener
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${DRC_LISTENER_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DRC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

  zgw.documenten.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Documenten.WebApi/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Documenten.WebApi
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${DRC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DRC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
      FileSystemDocumentServiceSettings__DocumentRootPath: "drc_dms"
    networks:
      - oneground

  zgw.notificaties.messaging.listener:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Notificaties.Messaging.Listener/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Notificaties.Messaging.Listener
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${NRC_LISTENER_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_NRC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_NRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
      ConnectionStrings__HangfireConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_NRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

  zgw.notificaties.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Notificaties.WebApi/Dockerfile
    user: root
    volumes:
      - ../oneground-services-data/nrc-data:/app/data
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Notificaties.WebApi
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${NRC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      SeedData__kanalen: "/app/data/kanalen.json"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_NRC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_NRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

  zgw.referentielijsten.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Referentielijsten.WebApi/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Referentielijsten.WebApi
    ports:
      - ${RC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
    networks:
      - oneground

  zgw.zaken.webapi:
    build:
      context: ../
      dockerfile: src/OneGround.ZGW.Zaken.WebApi/Dockerfile
    user: root
    volumes:
      - ./oneground-certificates:/usr/local/share/ca-certificates:ro
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    command: ./OneGround.ZGW.Zaken.WebApi
    depends_on:
      postgres_docker_db:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - ${ZRC_PORT}:${ASPNETCORE_INTERNAL_PORT}
    env_file: "default.env"
    environment:
      ASPNETCORE_URLS: "http://*:${ASPNETCORE_INTERNAL_PORT}"
      ConnectionStrings__UserConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_ZRC_DB};Username=${POSTGRES_USER};Password=${POSTGRES_USER_PASSWORD}"
      ConnectionStrings__AdminConnectionString: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_ZRC_DB};Username=${POSTGRES_ADMIN};Password=${POSTGRES_ADMIN_PASSWORD}"
    networks:
      - oneground

volumes:
  postgres:
  ceph-etc:
  ceph-lib:
  kc-providers:

networks:
  oneground:
    driver: bridge
