// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneGround.ZGW.Documenten.DataModel;

#nullable disable

namespace OneGround.ZGW.Documenten.DataModel.Migrations.DrcDbContext2Migrations
{
    [DbContext(typeof(DrcDbContext2))]
    [Migration("20260124140404_make_table_lock_owned_and_auditable")]
    partial class make_table_lock_owned_and_auditable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:ci_collation", "@colStrength=secondary,@colStrength=secondary,icu,False")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneGround.ZGW.DataAccess.AuditTrail.AuditTrailRegel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AanmaakDatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aanmaakdatum");

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actie");

                    b.Property<string>("ActieWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actieweergave");

                    b.Property<string>("ApplicatieId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicatie_id");

                    b.Property<string>("ApplicatieWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicatieweergave");

                    b.Property<string>("Bron")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bron");

                    b.Property<string>("GebruikersId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gebruikers_id");

                    b.Property<string>("GebruikersWeergave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gebruikersweergave");

                    b.Property<string>("HoofdObject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hoofdobject");

                    b.Property<Guid?>("HoofdObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoofdobject_id");

                    b.Property<string>("Nieuw")
                        .HasColumnType("jsonb")
                        .HasColumnName("nieuw");

                    b.Property<string>("Oud")
                        .HasColumnType("jsonb")
                        .HasColumnName("oud");

                    b.Property<string>("RequestId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resourceurl");

                    b.Property<string>("ResourceWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceweergave");

                    b.Property<int>("Resultaat")
                        .HasColumnType("integer")
                        .HasColumnName("resultaat");

                    b.Property<string>("Toelichting")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("toelichting");

                    b.HasKey("Id");

                    b.HasIndex("HoofdObjectId");

                    b.ToTable("audittrail");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.Migrations.FinishedDataMigration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("text")
                        .HasColumnName("application_version");

                    b.Property<DateTime>("Executed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("finished_data_migrations");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.NumberGenerator.OrganisatieNummer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("EntiteitNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entiteit");

                    b.Property<string>("Formaat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formaat");

                    b.Property<long>("HuidigNummer")
                        .HasColumnType("bigint")
                        .HasColumnName("huidig_nummer");

                    b.Property<string>("HuidigNummerEntiteit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("huidig_nummer_entiteit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("Rsin")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("rsin");

                    b.HasKey("Id");

                    b.ToTable("organisatie_nummers");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.Authorization.TempInformatieObjectAuthorization", b =>
                {
                    b.Property<string>("InformatieObjectType")
                        .HasColumnType("text");

                    b.Property<int>("MaximumVertrouwelijkheidAanduiding")
                        .HasColumnType("integer");

                    b.HasKey("InformatieObjectType");

                    b.ToTable("TempInformatieObjectAuthorization", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.ToView("TempInformatieObjectAuthorization", (string)null);
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.BestandsDeel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnkelvoudigInformatieObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobject_id");

                    b.Property<int>("Omvang")
                        .HasColumnType("integer")
                        .HasColumnName("omvang");

                    b.Property<string>("UploadPartId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("uploadpart_id");

                    b.Property<int>("Volgnummer")
                        .HasColumnType("integer")
                        .HasColumnName("volgnummer");

                    b.Property<bool>("Voltooid")
                        .HasColumnType("boolean")
                        .HasColumnName("voltooid");

                    b.HasKey("Id");

                    b.HasIndex("EnkelvoudigInformatieObjectId");

                    b.ToTable("bestandsdelen");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auteur")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auteur");

                    b.Property<DateTime>("BeginRegistratie")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("beginregistratie");

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("beschrijving");

                    b.Property<string>("Bestandsnaam")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bestandsnaam");

                    b.Property<long>("Bestandsomvang")
                        .HasColumnType("bigint")
                        .HasColumnName("bestandsomvang");

                    b.Property<string>("Bronorganisatie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bronorganisatie");

                    b.Property<Guid>("CatalogusId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogus_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateOnly?>("CreatieDatum")
                        .HasColumnType("date")
                        .HasColumnName("creatiedatum");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid>("EnkelvoudigInformatieObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobject_id ");

                    b.Property<Guid>("EnkelvoudigInformatieObjectLockId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobject_lock_id");

                    b.Property<string>("Formaat")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("formaat");

                    b.Property<string>("Identificatie")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("identificatie");

                    b.Property<bool?>("IndicatieGebruiksrecht")
                        .HasColumnType("boolean")
                        .HasColumnName("indicatiegebruiksrecht");

                    b.Property<string>("InformatieObjectType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("informatieobjecttype");

                    b.Property<string>("Inhoud")
                        .HasColumnType("text")
                        .HasColumnName("inhoud");

                    b.Property<bool>("InhoudIsVervallen")
                        .HasColumnType("boolean")
                        .HasColumnName("inhoud_is_vervallen");

                    b.Property<int>("Integriteit_Algoritme")
                        .HasColumnType("integer")
                        .HasColumnName("integriteit_algoritme");

                    b.Property<DateOnly?>("Integriteit_Datum")
                        .HasColumnType("date")
                        .HasColumnName("integriteit_datum");

                    b.Property<string>("Integriteit_Waarde")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("integriteit_waarde");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("MultiPartDocumentId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("multipartdocument_id");

                    b.Property<DateOnly?>("Ondertekening_Datum")
                        .HasColumnType("date")
                        .HasColumnName("ondertekening_datum");

                    b.Property<int?>("Ondertekening_Soort")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("ondertekening_soort");

                    b.Property<DateOnly?>("OntvangstDatum")
                        .HasColumnType("date")
                        .HasColumnName("ontvangstdatum");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Taal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("taal");

                    b.Property<string>("Titel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titel");

                    b.Property<List<string>>("Trefwoorden")
                        .HasColumnType("text[]")
                        .HasColumnName("trefwoorden");

                    b.Property<string>("Verschijningsvorm")
                        .HasColumnType("text")
                        .HasColumnName("verschijningsvorm");

                    b.Property<int>("Versie")
                        .HasColumnType("integer")
                        .HasColumnName("versie");

                    b.Property<int?>("Vertrouwelijkheidaanduiding")
                        .HasColumnType("integer")
                        .HasColumnName("vertrouwelijkheidaanduiding");

                    b.Property<DateOnly?>("VerzendDatum")
                        .HasColumnType("date")
                        .HasColumnName("verzenddatum");

                    b.HasKey("Id");

                    b.HasIndex("Bronorganisatie");

                    b.HasIndex("EnkelvoudigInformatieObjectId");

                    b.HasIndex("EnkelvoudigInformatieObjectLockId")
                        .HasDatabaseName("IX_enkelvoudiginformatieobjecten_2_enkelvoudiginformatieobjec~1");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_e0_light_covering");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "Owner", "Vertrouwelijkheidaanduiding", "EnkelvoudigInformatieObjectId" });

                    b.HasIndex("Identificatie");

                    b.HasIndex("InformatieObjectType");

                    b.HasIndex("Inhoud");

                    b.HasIndex("Owner");

                    b.HasIndex("Owner", "Id", "Vertrouwelijkheidaanduiding");

                    b.HasIndex("Owner", "Inhoud", "Vertrouwelijkheidaanduiding")
                        .IsDescending(false, false, true);

                    b.HasIndex("Vertrouwelijkheidaanduiding", "Id", "Owner");

                    b.HasIndex("Owner", "EnkelvoudigInformatieObjectId", "Versie", "Vertrouwelijkheidaanduiding")
                        .IsDescending(false, false, true, false);

                    b.HasIndex("Owner", "Inhoud", "Vertrouwelijkheidaanduiding", "EnkelvoudigInformatieObjectId")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_enkelvoudiginformatieobjecten_2_owner_inhoud_vertrouwelijk~1")
                        .HasFilter("Bestandsomvang IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Owner", "Inhoud", "Vertrouwelijkheidaanduiding", "EnkelvoudigInformatieObjectId"), new[] { "Bestandsomvang" });

                    b.ToTable("enkelvoudiginformatieobjecten_2");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectLock2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("Lock")
                        .HasColumnType("text")
                        .HasColumnName("lock");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.ToTable("enkelvoudiginformatieobject_locks_2");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.GebruiksRecht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<DateTime?>("Einddatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("einddatum");

                    b.Property<Guid>("EnkelvoudigInformatieObjectLockId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobjectlock_id");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("OmschrijvingVoorwaarden")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("omschrijvingvoorwaarden");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdatum");

                    b.HasKey("Id");

                    b.HasIndex("EnkelvoudigInformatieObjectLockId");

                    b.ToTable("gebruiksrechten");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.ObjectInformatieObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid>("EnkelvoudigInformatieObjectLockId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobjectlock_id");

                    b.Property<Guid>("InformatieObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("object")
                        .UseCollation("ci_collation");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("objecttype");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.HasIndex("EnkelvoudigInformatieObjectLockId");

                    b.HasIndex("InformatieObjectId");

                    b.HasIndex("Object");

                    b.HasIndex("Object", "InformatieObjectId", "ObjectType")
                        .IsUnique();

                    b.ToTable("objectinformatieobjecten");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.Verzending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AardRelatie")
                        .HasColumnType("smallint")
                        .HasColumnName("aardrelatie");

                    b.Property<string>("Betrokkene")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("betrokkene")
                        .UseCollation("ci_collation");

                    b.Property<BinnenlandsCorrespondentieAdres>("BinnenlandsCorrespondentieAdres")
                        .HasColumnType("jsonb")
                        .HasColumnName("binnenlandsCorrespondentieadres");

                    b.Property<BuitenlandsCorrespondentieAdres>("BuitenlandsCorrespondentieAdres")
                        .HasColumnType("jsonb")
                        .HasColumnName("buitenlandsCorrespondentieadres");

                    b.Property<string>("Contactpersoon")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contactpersoon");

                    b.Property<string>("ContactpersoonNaam")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contactpersoonnaam");

                    b.Property<CorrespondentiePostadres>("CorrespondentiePostadres")
                        .HasColumnType("jsonb")
                        .HasColumnName("correspondentiepostadres");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("EmailAdres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emailadres");

                    b.Property<Guid>("EnkelvoudigInformatieObjectLockId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobjectlock_id");

                    b.Property<string>("Faxnummer")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("faxnummer");

                    b.Property<bool>("MijnOverheid")
                        .HasColumnType("boolean")
                        .HasColumnName("mijnoverheid");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<DateOnly?>("Ontvangstdatum")
                        .HasColumnType("date")
                        .HasColumnName("ontvangstdatum");

                    b.Property<string>("Telefoonnummer")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefoonnummer");

                    b.Property<string>("Toelichting")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("toelichting");

                    b.Property<DateOnly?>("Verzenddatum")
                        .HasColumnType("date")
                        .HasColumnName("verzenddatum");

                    b.HasKey("Id");

                    b.HasIndex("AardRelatie");

                    b.HasIndex("Betrokkene");

                    b.HasIndex("EnkelvoudigInformatieObjectLockId");

                    b.ToTable("verzendingen");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.BestandsDeel", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject2", "EnkelvoudigInformatieObject")
                        .WithMany("BestandsDelen")
                        .HasForeignKey("EnkelvoudigInformatieObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObject");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject2", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectLock2", "EnkelvoudigInformatieObjectLock")
                        .WithMany("EnkelvoudigInformatieObjecten")
                        .HasForeignKey("EnkelvoudigInformatieObjectLockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObjectLock");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.GebruiksRecht", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectLock2", "EnkelvoudigInformatieObjectLock")
                        .WithMany("GebruiksRechten")
                        .HasForeignKey("EnkelvoudigInformatieObjectLockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObjectLock");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.ObjectInformatieObject", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectLock2", "EnkelvoudigInformatieObjectLock")
                        .WithMany("ObjectInformatieObjecten")
                        .HasForeignKey("EnkelvoudigInformatieObjectLockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObjectLock");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.Verzending", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectLock2", "EnkelvoudigInformatieObjectLock")
                        .WithMany("Verzendingen")
                        .HasForeignKey("EnkelvoudigInformatieObjectLockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObjectLock");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject2", b =>
                {
                    b.Navigation("BestandsDelen");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectLock2", b =>
                {
                    b.Navigation("EnkelvoudigInformatieObjecten");

                    b.Navigation("GebruiksRechten");

                    b.Navigation("ObjectInformatieObjecten");

                    b.Navigation("Verzendingen");
                });
#pragma warning restore 612, 618
        }
    }
}
