// <auto-generated/>
#pragma warning disable CS0618
using KeycloakSetup.Client.Admin.Realms.Item.Clients.Item.ProtocolMappers;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KeycloakSetup.Client.Admin.Realms.Item.Clients.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\realms\{realm}\clients\{client-uuid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientUuItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The protocolMappers property</summary>
        public global::KeycloakSetup.Client.Admin.Realms.Item.Clients.Item.ProtocolMappers.ProtocolMappersRequestBuilder ProtocolMappers
        {
            get => new global::KeycloakSetup.Client.Admin.Realms.Item.Clients.Item.ProtocolMappers.ProtocolMappersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KeycloakSetup.Client.Admin.Realms.Item.Clients.Item.ClientUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientUuItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/realms/{realm}/clients/{client%2Duuid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KeycloakSetup.Client.Admin.Realms.Item.Clients.Item.ClientUuItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientUuItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/realms/{realm}/clients/{client%2Duuid}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
