// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneGround.ZGW.Documenten.DataModel;

#nullable disable

namespace OneGround.ZGW.Documenten.DataModel.Migrations
{
    [DbContext(typeof(DrcDbContext))]
    [Migration("20250516153530_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:ci_collation", "@colStrength=secondary,@colStrength=secondary,icu,False")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneGround.ZGW.DataAccess.AuditTrail.AuditTrailRegel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AanmaakDatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aanmaakdatum");

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actie");

                    b.Property<string>("ActieWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actieweergave");

                    b.Property<string>("ApplicatieId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicatie_id");

                    b.Property<string>("ApplicatieWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicatieweergave");

                    b.Property<string>("Bron")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bron");

                    b.Property<string>("GebruikersId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gebruikers_id");

                    b.Property<string>("GebruikersWeergave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gebruikersweergave");

                    b.Property<string>("HoofdObject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hoofdobject");

                    b.Property<Guid?>("HoofdObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("hoofdobject_id");

                    b.Property<string>("Nieuw")
                        .HasColumnType("jsonb")
                        .HasColumnName("nieuw");

                    b.Property<string>("Oud")
                        .HasColumnType("jsonb")
                        .HasColumnName("oud");

                    b.Property<string>("RequestId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_id");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resourceurl");

                    b.Property<string>("ResourceWeergave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceweergave");

                    b.Property<int>("Resultaat")
                        .HasColumnType("integer")
                        .HasColumnName("resultaat");

                    b.Property<string>("Toelichting")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("toelichting");

                    b.HasKey("Id");

                    b.HasIndex("HoofdObjectId");

                    b.ToTable("audittrail");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.Migrations.FinishedDataMigration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("text")
                        .HasColumnName("application_version");

                    b.Property<DateTime>("Executed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("finished_data_migrations");
                });

            modelBuilder.Entity("OneGround.ZGW.DataAccess.NumberGenerator.OrganisatieNummer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("EntiteitNaam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entiteit");

                    b.Property<string>("Formaat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formaat");

                    b.Property<long>("HuidigNummer")
                        .HasColumnType("bigint")
                        .HasColumnName("huidig_nummer");

                    b.Property<string>("HuidigNummerEntiteit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("huidig_nummer_entiteit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("Rsin")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("rsin");

                    b.HasKey("Id");

                    b.ToTable("organisatie_nummers");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.BestandsDeel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnkelvoudigInformatieObjectVersieId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobjectversie_id");

                    b.Property<int>("Omvang")
                        .HasColumnType("integer")
                        .HasColumnName("omvang");

                    b.Property<string>("UploadPartId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("uploadpart_id");

                    b.Property<int>("Volgnummer")
                        .HasColumnType("integer")
                        .HasColumnName("volgnummer");

                    b.Property<bool>("Voltooid")
                        .HasColumnType("boolean")
                        .HasColumnName("voltooid");

                    b.HasKey("Id");

                    b.HasIndex("EnkelvoudigInformatieObjectVersieId");

                    b.ToTable("bestandsdelen");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<bool?>("IndicatieGebruiksrecht")
                        .HasColumnType("boolean")
                        .HasColumnName("indicatiegebruiksrecht");

                    b.Property<string>("InformatieObjectType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("informatieobjecttype");

                    b.Property<Guid?>("LatestEnkelvoudigInformatieObjectVersieId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_enkelvoudiginformatieobjectversie_id");

                    b.Property<string>("Lock")
                        .HasColumnType("text")
                        .HasColumnName("lock");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.HasIndex("InformatieObjectType");

                    b.HasIndex("LatestEnkelvoudigInformatieObjectVersieId")
                        .IsUnique();

                    b.HasIndex("Owner");

                    b.HasIndex("Owner", "InformatieObjectType", "LatestEnkelvoudigInformatieObjectVersieId");

                    b.ToTable("enkelvoudiginformatieobjecten");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectVersie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auteur")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auteur");

                    b.Property<DateTime>("BeginRegistratie")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("beginregistratie");

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("beschrijving");

                    b.Property<string>("Bestandsnaam")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bestandsnaam");

                    b.Property<long>("Bestandsomvang")
                        .HasColumnType("bigint")
                        .HasColumnName("bestandsomvang");

                    b.Property<string>("Bronorganisatie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bronorganisatie");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateOnly?>("CreatieDatum")
                        .HasColumnType("date")
                        .HasColumnName("creatiedatum");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid>("EnkelvoudigInformatieObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("enkelvoudiginformatieobject_id");

                    b.Property<string>("Formaat")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("formaat");

                    b.Property<string>("Identificatie")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("identificatie");

                    b.Property<string>("Inhoud")
                        .HasColumnType("text")
                        .HasColumnName("inhoud");

                    b.Property<bool>("InhoudIsVervallen")
                        .HasColumnType("boolean")
                        .HasColumnName("inhoud_is_vervallen");

                    b.Property<int>("Integriteit_Algoritme")
                        .HasColumnType("integer")
                        .HasColumnName("integriteit_algoritme");

                    b.Property<DateOnly?>("Integriteit_Datum")
                        .HasColumnType("date")
                        .HasColumnName("integriteit_datum");

                    b.Property<string>("Integriteit_Waarde")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("integriteit_waarde");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("MultiPartDocumentId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("multipartdocument_id");

                    b.Property<DateOnly?>("Ondertekening_Datum")
                        .HasColumnType("date")
                        .HasColumnName("ondertekening_datum");

                    b.Property<int?>("Ondertekening_Soort")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("ondertekening_soort");

                    b.Property<DateOnly?>("OntvangstDatum")
                        .HasColumnType("date")
                        .HasColumnName("ontvangstdatum");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Taal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("taal");

                    b.Property<string>("Titel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titel");

                    b.Property<List<string>>("Trefwoorden")
                        .HasColumnType("text[]")
                        .HasColumnName("trefwoorden");

                    b.Property<string>("Verschijningsvorm")
                        .HasColumnType("text")
                        .HasColumnName("verschijningsvorm");

                    b.Property<int>("Versie")
                        .HasColumnType("integer")
                        .HasColumnName("versie");

                    b.Property<int?>("Vertrouwelijkheidaanduiding")
                        .HasColumnType("integer")
                        .HasColumnName("vertrouwelijkheidaanduiding");

                    b.Property<DateOnly?>("VerzendDatum")
                        .HasColumnType("date")
                        .HasColumnName("verzenddatum");

                    b.HasKey("Id");

                    b.HasIndex("Bronorganisatie");

                    b.HasIndex("EnkelvoudigInformatieObjectId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_e0_light_covering");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "Owner", "Vertrouwelijkheidaanduiding", "EnkelvoudigInformatieObjectId" });

                    b.HasIndex("Identificatie");

                    b.HasIndex("Inhoud");

                    b.HasIndex("Bronorganisatie", "Identificatie", "Versie")
                        .IsUnique();

                    b.HasIndex("Owner", "Id", "Vertrouwelijkheidaanduiding");

                    b.HasIndex("Vertrouwelijkheidaanduiding", "Id", "Owner");

                    b.HasIndex("Owner", "EnkelvoudigInformatieObjectId", "Versie", "Vertrouwelijkheidaanduiding");

                    b.ToTable("enkelvoudiginformatieobjectversies");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.GebruiksRecht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<DateTime?>("Einddatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("einddatum");

                    b.Property<Guid>("InformatieObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("informatieobject_id");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("OmschrijvingVoorwaarden")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("omschrijvingvoorwaarden");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdatum");

                    b.HasKey("Id");

                    b.HasIndex("InformatieObjectId");

                    b.ToTable("gebruiksrechten");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.InformatieObjectAuthorization", b =>
                {
                    b.Property<string>("InformatieObjectType")
                        .HasColumnType("text");

                    b.Property<int>("MaximumVertrouwelijkheidAanduiding")
                        .HasColumnType("integer");

                    b.HasKey("InformatieObjectType");

                    b.ToTable("#InformatieObjectAuthorization", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.ObjectInformatieObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid>("InformatieObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("informatieobject_id");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("object")
                        .UseCollation("ci_collation");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer")
                        .HasColumnName("objecttype");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.HasIndex("InformatieObjectId");

                    b.HasIndex("Object");

                    b.HasIndex("Object", "InformatieObjectId", "ObjectType")
                        .IsUnique();

                    b.ToTable("objectinformatieobjecten");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.Verzending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AardRelatie")
                        .HasColumnType("smallint")
                        .HasColumnName("aardrelatie");

                    b.Property<string>("Betrokkene")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("betrokkene")
                        .UseCollation("ci_collation");

                    b.Property<BinnenlandsCorrespondentieAdres>("BinnenlandsCorrespondentieAdres")
                        .HasColumnType("jsonb")
                        .HasColumnName("binnenlandsCorrespondentieadres");

                    b.Property<BuitenlandsCorrespondentieAdres>("BuitenlandsCorrespondentieAdres")
                        .HasColumnType("jsonb")
                        .HasColumnName("buitenlandsCorrespondentieadres");

                    b.Property<string>("Contactpersoon")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contactpersoon");

                    b.Property<string>("ContactpersoonNaam")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contactpersoonnaam");

                    b.Property<CorrespondentiePostadres>("CorrespondentiePostadres")
                        .HasColumnType("jsonb")
                        .HasColumnName("correspondentiepostadres");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creationtime");

                    b.Property<string>("EmailAdres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emailadres");

                    b.Property<string>("Faxnummer")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("faxnummer");

                    b.Property<Guid>("InformatieObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("informatieobject_id");

                    b.Property<bool>("MijnOverheid")
                        .HasColumnType("boolean")
                        .HasColumnName("mijnoverheid");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificationtime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modifiedby");

                    b.Property<DateOnly?>("Ontvangstdatum")
                        .HasColumnType("date")
                        .HasColumnName("ontvangstdatum");

                    b.Property<string>("Telefoonnummer")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefoonnummer");

                    b.Property<string>("Toelichting")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("toelichting");

                    b.Property<DateOnly?>("Verzenddatum")
                        .HasColumnType("date")
                        .HasColumnName("verzenddatum");

                    b.HasKey("Id");

                    b.HasIndex("AardRelatie");

                    b.HasIndex("Betrokkene");

                    b.HasIndex("InformatieObjectId");

                    b.ToTable("verzendingen");
                });

            modelBuilder.Entity("Thinktecture.EntityFrameworkCore.TempTables.TempTable<string>", b =>
                {
                    b.Property<string>("Column1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("#TempTable<string>", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.BestandsDeel", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectVersie", "EnkelvoudigInformatieObjectVersie")
                        .WithMany("BestandsDelen")
                        .HasForeignKey("EnkelvoudigInformatieObjectVersieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObjectVersie");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectVersie", "LatestEnkelvoudigInformatieObjectVersie")
                        .WithOne("LatestEnkelvoudigInformatieObject")
                        .HasForeignKey("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", "LatestEnkelvoudigInformatieObjectVersieId");

                    b.Navigation("LatestEnkelvoudigInformatieObjectVersie");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectVersie", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", "EnkelvoudigInformatieObject")
                        .WithMany("EnkelvoudigInformatieObjectVersies")
                        .HasForeignKey("EnkelvoudigInformatieObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnkelvoudigInformatieObject");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.GebruiksRecht", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", "InformatieObject")
                        .WithMany("GebruiksRechten")
                        .HasForeignKey("InformatieObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformatieObject");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.ObjectInformatieObject", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", "InformatieObject")
                        .WithMany("ObjectInformatieObjecten")
                        .HasForeignKey("InformatieObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformatieObject");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.Verzending", b =>
                {
                    b.HasOne("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", "InformatieObject")
                        .WithMany("Verzendingen")
                        .HasForeignKey("InformatieObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformatieObject");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObject", b =>
                {
                    b.Navigation("EnkelvoudigInformatieObjectVersies");

                    b.Navigation("GebruiksRechten");

                    b.Navigation("ObjectInformatieObjecten");

                    b.Navigation("Verzendingen");
                });

            modelBuilder.Entity("OneGround.ZGW.Documenten.DataModel.EnkelvoudigInformatieObjectVersie", b =>
                {
                    b.Navigation("BestandsDelen");

                    b.Navigation("LatestEnkelvoudigInformatieObject");
                });
#pragma warning restore 612, 618
        }
    }
}
