#
# Docker Compose for the OneGround Autorisaties API (AC).
#
# This file defines the AC service container. For full setup instructions,
# please refer to the README.md file.
#
name: oneground-autorisaties-api

services:
  oneground.autorisaties.webapi:
    image: ghcr.io/oneground/autorisaties-api:1.0
    restart: unless-stopped
    ports:
      # You can change the host port (5009) if it conflicts with another service.
      - "5009:5000"
    env_file:
      - ".env"
    networks:
      - external_network

networks:
  external_network:
    # IMPORTANT: This must connect to the same network as your other services
    # (Postgres, RabbitMQ, Redis) for the API to function.
    name: bridge # <-- CHANGE THIS to your existing network name.
    external: true
