#
# Docker Compose for the OneGround Catalogi API (ZTC).
#
# This file defines the ZTC service container. For full setup instructions,
# please refer to the README.md file.
#
name: oneground-catalogi-api

services:
  oneground.catalogi.webapi:
    image: ghcr.io/oneground/catalogi-api:1.3
    restart: unless-stopped
    ports:
      # You can change the host port (5011) if it conflicts with another service.
      - "5011:5000"
    env_file:
      - ".env"
    networks:
      - external_network

networks:
  external_network:
    # IMPORTANT: This must connect to the same network as your other services
    # (Postgres, RabbitMQ, Redis) for the API to function.
    name: bridge # <-- CHANGE THIS to your existing network name.
    external: true
