name: Create and publish Autorisaties Docker image

on:
  push:
    branches:
      - FUND-1852
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Autorisaties.*/**'
  pull_request:
    branches:
        - FUND-1852
        - main
  workflow_dispatch:

jobs:
  build-and-publish-autorisaties-api-image:   
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      contents: write
      packages: write
    with:
      service_name: 'x-test-oneground-autorisaties-api'
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Autorisaties.WebApi/Dockerfile'
      context: '.'
 
  check_for_readme_changes:
    runs-on: ubuntu-latest
    outputs:
      readme_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes in README
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            src/OneGround.ZGW.Autorisaties.WebApi/README.md

  update-docker-hub-repository:
    needs: check_for_readme_changes
    if: needs.check_for_readme_changes.outputs.readme_changed == 'true'
    uses: ./.github/workflows/docker-hub-update.yml
    with:
      repository_name: 'x-test-oneground-autorisaties-api'
      description: 'Updated description for the Docker Hub repository'
      readme_filepath: './src/OneGround.ZGW.Autorisaties.WebApi/README.md'