name: Create and publish Autorisaties Docker image

on:
  push:
    branches:
      - FUND-1852
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Autorisaties.*/**'
  pull_request:
    branches:
      - FUND-1852
      - main
  workflow_dispatch:

jobs:
  build-and-publish-autorisaties-image:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      version: 1.0.${{ github.run_number }}
      service_name: 'autorisaties'
      docker_file: './src/OneGround.ZGW.Autorisaties.WebApi/Dockerfile'
      context: '.'