name: Create and publish Autorisaties Docker image

on:
  push:
    branches:
      - FUND-1852
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Autorisaties.*/**'
  pull_request:
    branches:
        - FUND-1852
        - main
  workflow_dispatch:

jobs:
  build-and-publish-autorisaties-api-image:   
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      service_name: 'x-oneground-autorisaties-api'
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Autorisaties.WebApi/Dockerfile'
      context: '.'