name: Create and publish Autorisaties Docker image

on:
  push:
    branches:     
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Autorisaties.*/**'
  pull_request:
    branches:
        - FUND-1852
        - main
  workflow_dispatch:

jobs:
  build-and-publish-autorisaties-api-image:   
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      contents: write
      packages: write
    with:
      service_name: 'x-test-3-autorisaties-api'
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Autorisaties.WebApi/Dockerfile'
      context: '.' 
      publish_to_docker_hub: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
 
  update-docker-hub-repository:   
    uses: ./.github/workflows/docker-hub-update.yml
    with:
      repository_name: 'x-test-3-autorisaties-api'
      description: 'OneGround implementation of ZGW Zaken API (from Netherlands VNG standard)'
      readme_filepath: './src/OneGround.ZGW.Autorisaties.WebApi/README.md'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}