name: Create and publish Autorisaties Docker image

on:
  push:
    branches:
      - FUND-1852
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Autorisaties.*/**'
  pull_request:
    branches:
        - FUND-1852
        - main
  workflow_dispatch:

env:
  SERVICE_NAME: 'x-test-oneground-autorisaties-api'

jobs:
  build-and-publish-autorisaties-api-image:   
    uses: ./.github/workflows/docker-build-and-push.yml
    permissions:
      contents: write
      packages: write
    with:
      service_name: ${{ env.SERVICE_NAME }}
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Autorisaties.WebApi/Dockerfile'
      context: '.' 
 
  update-docker-hub-repository:   
    uses: ./.github/workflows/docker-hub-update.yml
    with:
      repository_name: ${{ env.SERVICE_NAME }}
      description: 'OneGround Autorisaties API'
      readme_filepath: './src/OneGround.ZGW.Autorisaties.WebApi/README.md'