name: Create and publish Besluiten Docker image

on:
    push:
        branches:
            - main
        paths:
            - 'src/OneGround.ZGW.Common/**'
            - 'src/OneGround.ZGW.Common.*/**'
            - 'src/OneGround.ZGW.DataAccess/**'
            - 'src/OneGround.ZGW.Besluiten.*/**'
    workflow_dispatch:

jobs:
    build-and-publish-besluiten-api-image:
        uses: ./.github/workflows/docker-build-and-push.yml
        with:            
            service_name: 'besluiten-api'
            major_version: 1
            minor_version: 0
            docker_file: './src/OneGround.ZGW.Besluiten.WebApi/Dockerfile'
            context: '.'