name: Create and publish Besluiten Docker image

on:
    push:
        branches:
            - main
        paths:
            - 'src/OneGround.ZGW.Common/**'
            - 'src/OneGround.ZGW.Common.*/**'
            - 'src/OneGround.ZGW.DataAccess/**'
            - 'src/OneGround.ZGW.Besluiten.*/**'
    workflow_dispatch:

jobs:
    run_reusable_workflow:
        uses: ./.github/workflows/docker-build-and-push.yml
        with:
            version: 1.0.${{ github.run_number }}
            service_name: 'besluiten'
            docker_file: './src/OneGround.ZGW.Besluiten.WebApi/Dockerfile'
            context: '.'        