name: CI .NET Build & Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/ci-dotnet-build-and-test.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test .NET Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    env:
      SOLUTION_ROOT: '${{ github.workspace }}/src'
      SOLUTION_FILE: 'ZGW.Backend.slnf'
      SOLUTION_UNIT_TESTS: 'ZGW.UnitTests.slnf'
      BUILD_CONFIGURATION: 'Release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for changed files
      id: changed-files
      uses: .github/actions/check-changed-files
      with:
        paths_to_check: |
          src/
          .github/workflows/ci-dotnet-build-and-test.yml

    - name: Setup .NET
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      working-directory: ${{ env.SOLUTION_ROOT }}

    - name: Build
      if: steps.changed-files.outputs.any_changed == 'true'
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      working-directory: ${{ env.SOLUTION_ROOT }}

    - name: Test
      if: steps.changed-files.outputs.any_changed == 'true'
      run: dotnet test ${{ env.SOLUTION_UNIT_TESTS }} --configuration ${{ env.BUILD_CONFIGURATION }} --collect:"Code coverage" --logger trx --results-directory ${{ runner.temp }}
      working-directory: ${{ env.SOLUTION_ROOT }}