name: CI .NET Build & Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/ci-dotnet-build-and-test.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-files-changes:
    name: Check for files changes
    uses: ./.github/workflows/check-changes.yml
    with:
      # Paths to check for changes, ensuring the build only runs if relevant files are modified
      paths-to-check: >-
        'src/'
        '.github/workflows/ci-dotnet-build-and-test.yml'

  build-and-test:
    name: Build and Test .NET Project
    runs-on: ubuntu-latest
    needs: check-files-changes
    if: needs.check-files-changes.outputs.any_changed == 'true'

    env:
      SOLUTION_ROOT: '${{ github.workspace }}/src'
      SOLUTION_FILE: 'ZGW.Backend.slnf'
      SOLUTION_UNIT_TESTS: 'ZGW.UnitTests.slnf'
      BUILD_CONFIGURATION: 'Release'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      working-directory: ${{ env.SOLUTION_ROOT }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      working-directory: ${{ env.SOLUTION_ROOT }}

    - name: Test
      run: dotnet test ${{ env.SOLUTION_UNIT_TESTS }} --configuration ${{ env.BUILD_CONFIGURATION }} --collect:"Code coverage" --logger trx --results-directory ${{ runner.temp }}
      working-directory: ${{ env.SOLUTION_ROOT }}