name: Update Docker Hub Repository
on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
        description: 'Name of the Docker Hub repository'
      description:
        required: true
        type: string
        description: 'Description of the Docker Hub repository'
      readme_filepath:
        required: true
        type: string
        description: 'Path to the README file for the Docker Hub repository'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true     

env:
  NAMESPACE: oneground

jobs:
  update-docker-hub-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for README Changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            ${{ inputs.readme_filepath }}
      
      - name: Log secrets and variables
        run: |
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}"
         
      - name: Update Docker Hub repository
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.NAMESPACE }}/${{ inputs.repository_name }}
          short-description: ${{ inputs.description }}
          readme-filepath: ${{ inputs.readme_filepath }}