name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version of the OneGround service'
      service_name:
        required: true
        type: string
        description: 'Name of the OneGround service'
      docker_file:
        required: true
        type: string
        description: 'Path to the Dockerfile'
      context:
        required: true
        type: string
        description: 'Docker build context'
    secrets:
      GITHUB_TOKEN:
        required: true

env:
  REGISTRY: localhost:6500
  IMAGE_NAME: oneground-${{ inputs.service_name }}-api

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}     
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.docker_file }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
