name: Create and publish Notificaties Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Notificaties.*/**'
  workflow_dispatch:

jobs:
  build-and-publish-notificaties-api-image:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      service_name: 'oneground-notificaties-api'
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Notificaties.WebApi/Dockerfile'
      context: '.'

  build-and-publish-notificaties-listener-image:
    needs: build-and-publish-notificaties-api-image
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      service_name: 'oneground-notificaties-listener'
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Notificaties.Messaging.Listener/Dockerfile'
      context: '.'