name: Create and publish Referentielijsten Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Referentielijsten.*/**'
  workflow_dispatch:

jobs:
  build-and-publish-referentielijsten-api-image:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      service_name: 'referentielijsten-api'
      major_version: 1
      minor_version: 0
      docker_file: './src/OneGround.ZGW.Referentielijsten.WebApi/Dockerfile'
      context: '.'