name: Create and publish Zaken Docker image

on:
    push:
        branches:
            - main
        paths:
            - 'src/OneGround.ZGW.Common/**'
            - 'src/OneGround.ZGW.Common.*/**'
            - 'src/OneGround.ZGW.DataAccess/**'
            - 'src/OneGround.ZGW.Zaken.*/**'
    workflow_dispatch:

jobs:
    run_reusable_workflow:
        uses: ./.github/workflows/docker-build-and-push.yml
        with:
            version: 1.5.${{ github.run_number }}
            service_name: 'zaken'
            docker_file: './src/OneGround.ZGW.Zaken.WebApi/Dockerfile'
            context: '.'        