name: Create and publish Zaken Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'src/OneGround.ZGW.Common/**'
      - 'src/OneGround.ZGW.Common.*/**'
      - 'src/OneGround.ZGW.DataAccess/**'
      - 'src/OneGround.ZGW.Zaken.*/**'
  workflow_dispatch:

jobs:
  build-and-publish-zaken-api-image:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      service_name: 'oneground-zaken-api'
      major_version: 1
      minor_version: 5
      docker_file: './src/OneGround.ZGW.Zaken.WebApi/Dockerfile'
      context: '.'